test_that("min_neighbors",
{
  correct_min_neighbors_l_r <- c(1, 3, 1)
  correct_min_neighbors_r_r <- c(1, 3, 1)
  correct_min_neighbors_b_r <- c(1, 3, 1)
  correct_min_neighbors_a_r <- c(1, 3, 1)
  expect_equal(min_neighbors(b, w, "l")[idx_lp], correct_min_neighbors_l_r)
  expect_equal(min_neighbors(b, w, "r")[idx_lp], correct_min_neighbors_r_r)
  expect_equal(min_neighbors(b, w, "b")[idx_lp], correct_min_neighbors_b_r)
  expect_equal(min_neighbors(b, w, "a")[idx_lp], correct_min_neighbors_a_r)
  
  correct_min_neighbors_l_p <- c(1, 3, 1)
  correct_min_neighbors_r_p <- c(1, 3, 1)
  correct_min_neighbors_b_p <- c(1, 3, 1)
  correct_min_neighbors_a_p <- c(1, 3, 1)
  expect_equal(min_neighbors(b, w, "l", "p")[idx_lp], correct_min_neighbors_l_p)
  expect_equal(min_neighbors(b, w, "r", "p")[idx_lp], correct_min_neighbors_r_p)
  expect_equal(min_neighbors(b, w, "b", "p")[idx_lp], correct_min_neighbors_b_p)
  expect_equal(min_neighbors(b, w, "a", "p")[idx_lp], correct_min_neighbors_a_p)
  
  correct_min_neighbors_l_d <- c(NA, 3, NA)
  correct_min_neighbors_r_d <- c(NA, 3, NA)
  correct_min_neighbors_b_d <- c(NA, 3, NA)
  correct_min_neighbors_a_d <- c(NA, 3, NA)
  expect_equal_na_allowed(min_neighbors(b, w, "l", "d")[idx_lp], correct_min_neighbors_l_d)
  expect_equal_na_allowed(min_neighbors(b, w, "r", "d")[idx_lp], correct_min_neighbors_r_d)
  expect_equal_na_allowed(min_neighbors(b, w, "b", "d")[idx_lp], correct_min_neighbors_b_d)
  expect_equal_na_allowed(min_neighbors(b, w, "a", "d")[idx_lp], correct_min_neighbors_a_d)
})
