# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_localmaxima_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_detect_localmaxima_reflecting_cpp`, data, windowsize)
}

detect_localmaxima_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_detect_localmaxima_periodic_cpp`, data, windowsize)
}

detect_localmaxima_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_detect_localmaxima_discard_cpp`, data, windowsize)
}

max_neighbors_left_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_left_reflecting_cpp`, data, windowsize)
}

max_neighbors_right_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_right_reflecting_cpp`, data, windowsize)
}

max_neighbors_both_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_both_reflecting_cpp`, data, windowsize)
}

max_neighbors_all_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_all_reflecting_cpp`, data, windowsize)
}

max_neighbors_left_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_left_periodic_cpp`, data, windowsize)
}

max_neighbors_right_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_right_periodic_cpp`, data, windowsize)
}

max_neighbors_both_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_both_periodic_cpp`, data, windowsize)
}

max_neighbors_all_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_all_periodic_cpp`, data, windowsize)
}

max_neighbors_left_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_left_discard_cpp`, data, windowsize)
}

max_neighbors_right_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_right_discard_cpp`, data, windowsize)
}

max_neighbors_both_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_both_discard_cpp`, data, windowsize)
}

max_neighbors_all_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_max_neighbors_all_discard_cpp`, data, windowsize)
}

mean_neighbors_left_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_left_reflecting_cpp`, data, windowsize)
}

mean_neighbors_right_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_right_reflecting_cpp`, data, windowsize)
}

mean_neighbors_both_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_both_reflecting_cpp`, data, windowsize)
}

mean_neighbors_all_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_all_reflecting_cpp`, data, windowsize)
}

mean_neighbors_left_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_left_periodic_cpp`, data, windowsize)
}

mean_neighbors_right_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_right_periodic_cpp`, data, windowsize)
}

mean_neighbors_both_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_both_periodic_cpp`, data, windowsize)
}

mean_neighbors_all_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_all_periodic_cpp`, data, windowsize)
}

mean_neighbors_left_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_left_discard_cpp`, data, windowsize)
}

mean_neighbors_right_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_right_discard_cpp`, data, windowsize)
}

mean_neighbors_both_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_both_discard_cpp`, data, windowsize)
}

mean_neighbors_all_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_mean_neighbors_all_discard_cpp`, data, windowsize)
}

min_neighbors_left_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_left_reflecting_cpp`, data, windowsize)
}

min_neighbors_right_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_right_reflecting_cpp`, data, windowsize)
}

min_neighbors_both_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_both_reflecting_cpp`, data, windowsize)
}

min_neighbors_all_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_all_reflecting_cpp`, data, windowsize)
}

min_neighbors_left_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_left_periodic_cpp`, data, windowsize)
}

min_neighbors_right_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_right_periodic_cpp`, data, windowsize)
}

min_neighbors_both_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_both_periodic_cpp`, data, windowsize)
}

min_neighbors_all_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_all_periodic_cpp`, data, windowsize)
}

min_neighbors_left_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_left_discard_cpp`, data, windowsize)
}

min_neighbors_right_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_right_discard_cpp`, data, windowsize)
}

min_neighbors_both_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_both_discard_cpp`, data, windowsize)
}

min_neighbors_all_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_min_neighbors_all_discard_cpp`, data, windowsize)
}

sd_neighbors_left_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_left_reflecting_cpp`, data, windowsize)
}

sd_neighbors_right_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_right_reflecting_cpp`, data, windowsize)
}

sd_neighbors_both_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_both_reflecting_cpp`, data, windowsize)
}

sd_neighbors_all_reflecting_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_all_reflecting_cpp`, data, windowsize)
}

sd_neighbors_left_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_left_periodic_cpp`, data, windowsize)
}

sd_neighbors_right_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_right_periodic_cpp`, data, windowsize)
}

sd_neighbors_both_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_both_periodic_cpp`, data, windowsize)
}

sd_neighbors_all_periodic_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_all_periodic_cpp`, data, windowsize)
}

sd_neighbors_left_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_left_discard_cpp`, data, windowsize)
}

sd_neighbors_right_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_right_discard_cpp`, data, windowsize)
}

sd_neighbors_both_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_both_discard_cpp`, data, windowsize)
}

sd_neighbors_all_discard_cpp <- function(data, windowsize) {
    .Call(`_scorepeak_sd_neighbors_all_discard_cpp`, data, windowsize)
}

